<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Introduktion til netværksanalyse i R – Kursusmateriale til Virksomhedsstrategi i et netværksperspektiv</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-553db639d176b1f1e5eb8f34e19f9014.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Kursusmateriale til Virksomhedsstrategi i et netværksperspektiv</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Install_guide.html"> 
<span class="menu-text">Install and setup R</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./intro.html"> 
<span class="menu-text">Intro til R og Tidyverse</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./kursusmateriale.html"> 
<span class="menu-text">Kursusmateriale</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#indlæs-og-udvælg-data" id="toc-indlæs-og-udvælg-data" class="nav-link active" data-scroll-target="#indlæs-og-udvælg-data">Indlæs og udvælg data</a></li>
  <li><a href="#fra-data-til-netværksobjekter" id="toc-fra-data-til-netværksobjekter" class="nav-link" data-scroll-target="#fra-data-til-netværksobjekter">Fra data til netværksobjekter</a>
  <ul class="collapse">
  <li><a href="#adjacency-matricer" id="toc-adjacency-matricer" class="nav-link" data-scroll-target="#adjacency-matricer">Adjacency matricer</a>
  <ul class="collapse">
  <li><a href="#et-sæt-vertices" id="toc-et-sæt-vertices" class="nav-link" data-scroll-target="#et-sæt-vertices">Et sæt vertices</a></li>
  <li><a href="#to-sæt-vertices" id="toc-to-sæt-vertices" class="nav-link" data-scroll-target="#to-sæt-vertices">To sæt vertices</a></li>
  <li><a href="#graf-projektion" id="toc-graf-projektion" class="nav-link" data-scroll-target="#graf-projektion">graf projektion</a></li>
  </ul></li>
  <li><a href="#praktisk-eksempel-med-den17" id="toc-praktisk-eksempel-med-den17" class="nav-link" data-scroll-target="#praktisk-eksempel-med-den17">Praktisk eksempel med <em>den17</em></a></li>
  </ul></li>
  <li><a href="#netværksobjekter-fra-matricer-igraph" id="toc-netværksobjekter-fra-matricer-igraph" class="nav-link" data-scroll-target="#netværksobjekter-fra-matricer-igraph">Netværksobjekter fra matricer (<code>igraph()</code>)</a>
  <ul class="collapse">
  <li><a href="#monopartite-netværk" id="toc-monopartite-netværk" class="nav-link" data-scroll-target="#monopartite-netværk">(Monopartite) netværk</a></li>
  <li><a href="#bipartite-netværk" id="toc-bipartite-netværk" class="nav-link" data-scroll-target="#bipartite-netværk">(Bipartite) netværk</a></li>
  </ul></li>
  <li><a href="#netværksvisualisering" id="toc-netværksvisualisering" class="nav-link" data-scroll-target="#netværksvisualisering">Netværksvisualisering</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Introduktion til netværksanalyse i R</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>I denne øvelses-session skal vi indlæse et netværksdatasæt og lave den første simple netværksgraf. Datasættet vi kigger på er kommer vi i øvrigt til at gå meget mere i dybden med se <a href="session2.html">Session 2 (uge 7)</a>.</p>
<p><a href="scripts til undervisning/Session1.R" class="btn btn-primary">Download script</a></p>
<p>Først indlæser vi de pakker vi kommer til at bruge:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(igraph)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggraph)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Matrix)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="indlæs-og-udvælg-data" class="level1">
<h1>Indlæs og udvælg data</h1>
<p>Dernæst indlæser vi og gemmer datasættet <code>den17-no-nordic-letters.csv</code>, som ligger mappen <code>"/data"</code> i R projketet. Det kan også downloades her: <a href="data/den17-no-nordic-letters.csv" class="btn btn-primary">Download den17</a></p>
<p>Indlæs data med <code>read_csv()</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>den <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/den17-no-nordic-letters.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>I <a href="intro.html">“Intro til R og Tidyverse”</a> introducerede vi en række funktioner fra tidyverse’s dplyr pakke. Dem skal vi bruge nogle af her.</p>
<p>Først ser vi lige på hvad vores dataobjekt indeholder <code>glimpse()</code>. Det består af <code>56849</code> og <code>10</code> kolonner - eller variable:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>den <span class="sc">%&gt;%</span> <span class="fu">glimpse</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 56,849
Columns: 10
$ name            &lt;chr&gt; "Lars Eivind Kreken", "Mikael Ernst Joergensen", "Thom…
$ affiliation     &lt;chr&gt; "&amp; co", "&amp; co", "&amp; co", "&amp; co", "15. juni fonden (Best…
$ role            &lt;chr&gt; "Member", "Executive", "Chairman", "Member", "Chairman…
$ gender          &lt;chr&gt; "Men", "Men", "Men", "Men", "Men", "Men", "Women", "Wo…
$ tags            &lt;chr&gt; "Corporation, Media, Marketing, Commercials, Communica…
$ sector          &lt;chr&gt; "Corporations", "Corporations", "Corporations", "Corpo…
$ type            &lt;chr&gt; "Virksomhed (CVR)", "Virksomhed (CVR)", "Virksomhed (C…
$ cvr_person      &lt;dbl&gt; 4006470500, 4004059627, 4004304040, 4004062718, NA, 40…
$ cvr_affiliation &lt;dbl&gt; 21705535, 21705535, 21705535, 21705535, 15232102, 1523…
$ description     &lt;chr&gt; "Automatisk CVR import at 2016-03-12 17:45:41: BESTYRE…</code></pre>
</div>
</div>
<p>Lad os tjekke hvad sector variablen indeholder med <code>count()</code> - og også med <code>distinct()</code>, da vores data indeholde flere rækker for hver organisation (<code>affiliation</code>, som variablen med organisationsnavne hedder), da der er tale om et positionsdatasæt individ-rolle-organisation:</p>
<ul>
<li>Der er 9524 positioner i affiliations/organisationer, der har koden corporations.</li>
<li>Det svarer til 1454 unikke corporations.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>den <span class="sc">%&gt;%</span> <span class="fu">count</span>(sector, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 2
   sector           n
   &lt;chr&gt;        &lt;int&gt;
 1 NGO          17720
 2 State        13764
 3 Corporations  9524
 4 Foundations   6993
 5 VL_networks   3803
 6 Events        2270
 7 Parliament    1087
 8 Commissions    814
 9 Municipal      320
10 Organisation   227
11 Family         207
12 &lt;NA&gt;            83
13 Politics        37</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>den <span class="sc">%&gt;%</span> <span class="fu">distinct</span>(affiliation, sector) <span class="sc">%&gt;%</span> <span class="fu">count</span>(sector, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 2
   sector           n
   &lt;chr&gt;        &lt;int&gt;
 1 NGO           1550
 2 Corporations  1454
 3 Foundations   1174
 4 State         1085
 5 VL_networks    114
 6 Commissions     68
 7 Family          51
 8 Parliament      49
 9 Organisation    23
10 Municipal       22
11 Events          17
12 &lt;NA&gt;             9
13 Politics         3</code></pre>
</div>
</div>
<p>Lad os bruge <code>filter()</code> til at lave et nyt dataobjekt, der kun indeholder de rækker, hvor sector er lig <code>Corporations</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>den_corp <span class="ot">&lt;-</span> den <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sector <span class="sc">==</span> <span class="st">"Corporations"</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>den_corp <span class="sc">%&gt;%</span> <span class="fu">count</span>(affiliation, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,454 × 2
   affiliation                                        n
   &lt;chr&gt;                                          &lt;int&gt;
 1 TRE-FOR (Repraesentantskab)                      119
 2 Kromann Reumert                                   55
 3 Bech-Bruun                                        54
 4 Gorrissen Federspiel                              40
 5 Plesner                                           40
 6 EnergiMidt                                        31
 7 Lett Law Firm                                     27
 8 Koebenhavns Lufthavns Vaekstkomité (Medlemmer)    24
 9 Syd Energi (SE)                                   24
10 TDC (note)                                        24
# ℹ 1,444 more rows</code></pre>
</div>
</div>
</section>
<section id="fra-data-til-netværksobjekter" class="level1">
<h1>Fra data til netværksobjekter</h1>
<p>Netværksdata er ofte indsamlet i den form vi finder i <code>den17</code> datasættet. Altså som en såkaldt <code>edge-list</code>, der i to kolonner repræsenterer forbindelser mellem ‘noget’. I dette personer i en kolonne og organisationer. Det kunne for så vidt også være individer i en kolonne og individer i den anden (fx. facebook venskaber). Når vi skal omforme vores data til et format der muliggør netværksanalyse og -visualisering bruger vi R-pakken <code>igraph</code>.</p>
<p>Her det er fordel lige at få styr på et par matrix regneregler og begreber:</p>
<section id="adjacency-matricer" class="level2">
<h2 class="anchored" data-anchor-id="adjacency-matricer">Adjacency matricer</h2>
<p>Et at netværk (i matematiksprog en <em>graf</em> - som ikke er at forveksle med en graf som vi normalt kender den som fx en linje i et koordinatsystem) består af relationer mellem et eller to sæt af elementer, fx. relationer mellem individer (venskaber) eller relationer mellem individer og organisationer (poster/medlemskaber). Elementerne kalder vi <em>vertices</em> (eller noder) og forbindelserne kalder vi <em>edges</em>.</p>
<section id="et-sæt-vertices" class="level3">
<h3 class="anchored" data-anchor-id="et-sæt-vertices">Et sæt vertices</h3>
<p>Hvis netværket består af ét sæt af elementer, fx. individer, kalder vi matrix repræsentationen for en adjacency matrice (adjacent betyder ‘tilstødende’, altså ‘forbundet’). En adjacency matrice <span class="math inline">\(A\)</span> for et netværk med <span class="math inline">\(n\)</span>elementer <span class="math inline">\(V = \begin{pmatrix} v_1 &amp; v_2 &amp; \dots &amp; v_n\end{pmatrix}\)</span> definerer vi således som en <span class="math inline">\(n \times n\)</span> matrice <span class="math inline">\(A\)</span> hvor:</p>
<p><span class="math display">\[
a_{ij} =
\begin{cases}
1, &amp; \text{hvis der er en forbindelse mellem vertex } i \text{ og vertex } j \\
0, &amp; \text{eller}
\end{cases}
\]</span> dvs.</p>
<p><span class="math display">\[A =
\begin{pmatrix}
0 &amp; 1 &amp; 1 &amp; 0 \\
1 &amp; 0 &amp; 1 &amp; 1 \\
1 &amp; 1 &amp; 0 &amp; 1 \\
0 &amp; 1 &amp; 1 &amp; 0
\end{pmatrix}
\]</span></p>
</section>
<section id="to-sæt-vertices" class="level3">
<h3 class="anchored" data-anchor-id="to-sæt-vertices">To sæt vertices</h3>
<p>Hvis netværket derimod består af to distinkte sæt vertices, fx. individer og organisationer, hvor der kun er forbindelser på tværs af de to sæt om ikke indenfor dem, kalder vi det et <em>bipartite netværk</em>, kalder vi matrix repræsentationen en <em>biadjacency matrice</em> (nogen gange også incidence matrice).</p>
<p>En biadjacency matrice for et bipartite netværk med to sæt vertices <span class="math inline">\(V = \{ v_1, v_2, \dots, v_n \}\text{ og }U = \{ u_1, u_2, \dots, u_n \}\)</span> er således en <span class="math inline">\(n \times m\)</span> matrice <span class="math inline">\(B\)</span> hvor: <span class="math display">\[
B_{ij} =
\begin{cases}
1 &amp; \text{hvis der er en edge/forbindelse mellem vertex } u_i \text{ i sættet } U \text{ og vertex } v_j \text{ i sættet } V, \\
0 &amp; \text{hvis der ikke er en edge/forbindelse mellem } u_i \text{ og vertex } v_j.
\end{cases}
\]</span></p>
<p>dvs.</p>
<p><span class="math display">\[
B = \begin{pmatrix}
1 &amp; 1 &amp; 0 \\
0 &amp; 1 &amp; 0 \\
0 &amp; 0 &amp; 1 \\
1 &amp; 0 &amp; 1
\end{pmatrix}
\]</span></p>
</section>
<section id="graf-projektion" class="level3">
<h3 class="anchored" data-anchor-id="graf-projektion">graf projektion</h3>
<p>Vores bipartite netværk har som bekendt to forskellige typer af vertices <span class="math inline">\(V(individer) = \{ v_1, v_2, \dots, v_n \}\text{ og }U(organisationer) = \{ u_1, u_2, \dots, u_n \}\)</span>. Individ1 er forbundet til Organisation1 og Organisation2, Individ2 er forbundet til Organisation2… osv. Med lidt “simpel” matrix regning kan vi hurtigt udregne to nye netværk, nemlig <span class="math inline">\(Individ \times Individ\)</span> netværket (altså hvilke individer er forbundet ‘gennem’ en eller flere organisationer) og <span class="math inline">\(Organisation \times Organisation\)</span> netværket (altså hvilke organisationer er forbundet fordi de deler individer):</p>
<section id="individ-x-individ" class="level4">
<h4 class="anchored" data-anchor-id="individ-x-individ">individ x individ</h4>
<p>Ved at gange hele matricen <span class="math inline">\(B\)</span> med en transponeret version af <span class="math inline">\(B\)</span>, <span class="math inline">\(B^T\)</span> får vi en <span class="math inline">\(n \times n\)</span> matrice for <span class="math inline">\(V\)</span> sættet, altså en <span class="math inline">\(individ \times individ\)</span>:</p>
<p><span class="math display">\[M_v = B \times B^T = \begin{pmatrix}
\textcolor{red}{1} &amp; \textcolor{red}{1} &amp; \textcolor{red}{0} \\
\textcolor{blue}{0} &amp; \textcolor{blue}{1} &amp; \textcolor{blue}{0} \\
\textcolor{green}{0} &amp; \textcolor{green}{0} &amp; \textcolor{green}{1} \\
\textcolor{purple}{1} &amp; \textcolor{purple}{0} &amp; \textcolor{purple}{1}
\end{pmatrix}
\times
\begin{pmatrix}
\textcolor{red}{1} &amp; \textcolor{blue}{0} &amp; \textcolor{green}{0} &amp; \textcolor{purple}{1} \\
\textcolor{red}{1} &amp; \textcolor{blue}{1} &amp; \textcolor{green}{0} &amp; \textcolor{purple}{0} \\
\textcolor{red}{0} &amp; \textcolor{blue}{0} &amp; \textcolor{green}{1} &amp; \textcolor{purple}{1}
\end{pmatrix} \text{farverne repræsenterer individrækkerne}\]</span> <span class="math display">\[=\begin{pmatrix}
\textcolor{red}{1} \times \textcolor{red}{1} + \textcolor{red}{1} \times \textcolor{red}{0} + \textcolor{red}{0} \times \textcolor{red}{0} &amp;
\textcolor{red}{1} \times \textcolor{blue}{0} + \textcolor{red}{1} \times \textcolor{blue}{1} + \textcolor{red}{0} \times \textcolor{blue}{0} &amp;
\textcolor{red}{1} \times \textcolor{green}{0} + \textcolor{red}{1} \times \textcolor{green}{0} + \textcolor{red}{0} \times \textcolor{green}{1} &amp;
\textcolor{red}{1} \times \textcolor{purple}{1} + \textcolor{red}{1} \times \textcolor{purple}{0} + \textcolor{red}{0} \times \textcolor{purple}{1} \\
\textcolor{blue}{0} \times \textcolor{red}{1} + \textcolor{blue}{1} \times \textcolor{red}{0} + \textcolor{blue}{0} \times \textcolor{red}{0} &amp;
\textcolor{blue}{0} \times \textcolor{blue}{0} + \textcolor{blue}{1} \times \textcolor{blue}{1} + \textcolor{blue}{0} \times \textcolor{blue}{0} &amp;
\textcolor{blue}{0} \times \textcolor{green}{0} + \textcolor{blue}{1} \times \textcolor{green}{0} + \textcolor{blue}{0} \times \textcolor{green}{1} &amp;
\textcolor{blue}{0} \times \textcolor{purple}{1} + \textcolor{blue}{1} \times \textcolor{purple}{0} + \textcolor{blue}{0} \times \textcolor{purple}{1} \\
\textcolor{green}{0} \times \textcolor{red}{1} + \textcolor{green}{0} \times \textcolor{red}{0} + \textcolor{green}{1} \times \textcolor{red}{0} &amp;
\textcolor{green}{0} \times \textcolor{blue}{0} + \textcolor{green}{0} \times \textcolor{blue}{1} + \textcolor{green}{1} \times \textcolor{blue}{0} &amp;
\textcolor{green}{0} \times \textcolor{green}{0} + \textcolor{green}{0} \times \textcolor{green}{0} + \textcolor{green}{1} \times \textcolor{green}{1} &amp;
\textcolor{green}{0} \times \textcolor{purple}{1} + \textcolor{green}{0} \times \textcolor{purple}{0} + \textcolor{green}{1} \times \textcolor{purple}{1} \\
\textcolor{purple}{1} \times \textcolor{red}{1} + \textcolor{purple}{0} \times \textcolor{red}{0} + \textcolor{purple}{1} \times \textcolor{red}{0} &amp;
\textcolor{purple}{1} \times \textcolor{blue}{0} + \textcolor{purple}{0} \times \textcolor{blue}{1} + \textcolor{purple}{1} \times \textcolor{blue}{0} &amp;
\textcolor{purple}{1} \times \textcolor{green}{0} + \textcolor{purple}{0} \times \textcolor{green}{0} + \textcolor{purple}{1} \times \textcolor{green}{1} &amp;
\textcolor{purple}{1} \times \textcolor{purple}{1} + \textcolor{purple}{0} \times \textcolor{purple}{0} + \textcolor{purple}{1} \times \textcolor{purple}{1}  
\end{pmatrix}
\]</span></p>
<p><span class="math display">\[= \begin{pmatrix}
\textcolor{red}{2} &amp; 1 &amp; 0 &amp; 1 \\
1 &amp; \textcolor{blue}{1} &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; \textcolor{green}{1} &amp; 1 \\
1 &amp; 0 &amp; 1 &amp; \textcolor{purple}{2}
\end{pmatrix}
\]</span></p>
<p>Matrix <span class="math inline">\(M_v\)</span> fortæller os i diagonalen, hvor mange gange hvert individ ‘møder sig selv’ (læs: hvor mange organisationer de er medlem af), uden for diagonalen fortæller det os at i1 (individ1) har fælles organisationer med både både i2 og i4 mens i2 kun deler organisation med én, nemlig i1. I4 har også to fælles organisationer, nemlig med i1 og i3, mens i3 også kun har én fælles tilknytning, nemlig med i4.</p>
</section>
<section id="organisation-x-organisation" class="level4">
<h4 class="anchored" data-anchor-id="organisation-x-organisation">organisation x organisation</h4>
<p>Vi kan også gøre det omvendt: Ved at en transponeret version af <span class="math inline">\(B\)</span>, <span class="math inline">\(B^T\)</span>, med <span class="math inline">\(B\)</span> får vi en <span class="math inline">\(m \times m\)</span> matrice for <span class="math inline">\(U\)</span> sættet, altså en <span class="math inline">\(organisation \times organisation\)</span>:</p>
<p><span class="math display">\[M_u = B^T \times  B= \begin{pmatrix}
\textcolor{red}{1} &amp; \textcolor{red}{0} &amp; \textcolor{red}{0} &amp; \textcolor{red}{1} \\
\textcolor{blue}{1} &amp; \textcolor{blue}{1} &amp; \textcolor{blue}{0} &amp; \textcolor{blue}{0} \\
\textcolor{green}{0} &amp; \textcolor{green}{0} &amp; \textcolor{green}{1} &amp; \textcolor{green}{1}
\end{pmatrix}
\times
\begin{pmatrix}
\textcolor{red}{1} &amp; \textcolor{blue}{1} &amp; \textcolor{green}{0} \\
\textcolor{red}{0} &amp; \textcolor{blue}{1} &amp; \textcolor{green}{0} \\
\textcolor{red}{0} &amp; \textcolor{blue}{0} &amp; \textcolor{green}{1} \\
\textcolor{red}{1} &amp; \textcolor{blue}{0} &amp; \textcolor{green}{1}
\end{pmatrix} \text{farverne repræsenterer organisationskolonnerne}\]</span></p>
<p><span class="math display">\[=\begin{pmatrix}
\textcolor{red}{1} \times \textcolor{red}{1} + \textcolor{red}{0} \times \textcolor{red}{0} + \textcolor{red}{0} \times \textcolor{red}{0} + \textcolor{red}{1} \times \textcolor{red}{1} &amp;
\textcolor{red}{1} \times \textcolor{blue}{1} + \textcolor{red}{0} \times \textcolor{blue}{1} + \textcolor{red}{0} \times \textcolor{blue}{0} + \textcolor{red}{1} \times \textcolor{blue}{0}&amp;
\textcolor{red}{1} \times \textcolor{green}{0} + \textcolor{red}{0} \times \textcolor{green}{0} + \textcolor{red}{0} \times \textcolor{green}{1} + \textcolor{red}{1} \times \textcolor{green}{1} \\
\textcolor{blue}{1} \times \textcolor{red}{1} + \textcolor{blue}{1} \times \textcolor{red}{0} + \textcolor{blue}{0} \times \textcolor{red}{0} + \textcolor{blue}{0} \times \textcolor{red}{0} &amp;
\textcolor{blue}{1} \times \textcolor{blue}{1} + \textcolor{blue}{1} \times \textcolor{blue}{1} + \textcolor{blue}{0} \times \textcolor{blue}{0} + \textcolor{blue}{0} \times \textcolor{blue}{0} &amp;
\textcolor{blue}{1} \times \textcolor{green}{0} + \textcolor{blue}{1} \times \textcolor{green}{0} + \textcolor{blue}{0} \times \textcolor{green}{1}  + \textcolor{blue}{0} \times \textcolor{green}{1} \\
\textcolor{green}{0} \times \textcolor{red}{1} + \textcolor{green}{0} \times \textcolor{red}{1} + \textcolor{green}{1} \times \textcolor{red}{0} + \textcolor{green}{1} \times \textcolor{red}{1} &amp;
\textcolor{green}{0} \times \textcolor{blue}{1} + \textcolor{green}{0} \times \textcolor{blue}{1} + \textcolor{green}{1} \times \textcolor{blue}{0} + \textcolor{green}{1} \times \textcolor{blue}{0} &amp;
\textcolor{green}{0} \times \textcolor{green}{0} + \textcolor{green}{0} \times \textcolor{green}{0} + \textcolor{green}{1} \times \textcolor{green}{1} + \textcolor{green}{1} \times \textcolor{green}{1}
\end{pmatrix}
\]</span></p>
<p><span class="math display">\[= \begin{pmatrix}
\textcolor{red}{2} &amp; 1 &amp; 1 \\
1 &amp; \textcolor{blue}{2} &amp; 0 \\
1 &amp; 0 &amp; \textcolor{green}{2}
\end{pmatrix}
\]</span></p>
<p>Matrix <span class="math inline">\(M_u\)</span> fortæller os i diagonalen, hvor mange gange hver medlemmer hver organisation har. Uden for diagonalen fortæller det os nu at o1 (organisation1) deler et medlem med både o2 og o3 mens o2 kun deler medlem med én organisation, nemlig o1. o3 har også et individ med en anden organisation, nemlig med o1.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ovenstående var eksempler på hvordan vi ved hjælp af matrix regning kommer fra en biadjaceny matrice, <span class="math inline">\(B\)</span> med fx individer i rækker og organisationer i kolonner, til to forskellige adjacency matricer <span class="math inline">\(M_{individ \times individ}\)</span> og <span class="math inline">\(M_{organisation \times organisation}\)</span>.</p>
<ul>
<li><span class="math inline">\(M_{individ \times individ} = B \times B^T\)</span></li>
<li><span class="math inline">\(M_{organisation \times organisation} = B^T \times B\)</span></li>
</ul>
</div>
</div>
<p>I R kode er det meget nemmere end det ser ud…</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">i =</span> <span class="fu">c</span>(<span class="st">"ind1"</span>, <span class="st">"ind2"</span>, <span class="st">"ind3"</span>, <span class="st">"ind4"</span>), <span class="at">org1 =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">org2=</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">org3 =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">row.names =</span> <span class="st">"i"</span>) <span class="sc">%&gt;%</span> <span class="fu">as.matrix</span>()</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>x</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     org1 org2 org3
ind1    1    1    0
ind2    0    1    0
ind3    0    0    1
ind4    1    0    1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t</span>(x)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     ind1 ind2 ind3 ind4
org1    1    0    0    1
org2    1    1    0    0
org3    0    0    1    1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">%*%</span> <span class="fu">t</span>(x)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     ind1 ind2 ind3 ind4
ind1    2    1    0    1
ind2    1    1    0    0
ind3    0    0    1    1
ind4    1    0    1    2</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t</span>(x) <span class="sc">%*%</span> x</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     org1 org2 org3
org1    2    1    1
org2    1    2    0
org3    1    0    2</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="praktisk-eksempel-med-den17" class="level2">
<h2 class="anchored" data-anchor-id="praktisk-eksempel-med-den17">Praktisk eksempel med <em>den17</em></h2>
<p>lad os bruge det dataobjekt vi allerede har defineret, <em>den_corp</em>, som indeholder alle rækker fra <em>den17</em> som har <code>sector == "Corporations"</code>.</p>
<p>vi kan lige se, hvordan kolonnerne <code>name</code> og <code>affiliation</code> ser ud:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>den_corp <span class="sc">%&gt;%</span> <span class="fu">select</span>(name, affiliation) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9,524 × 2
   name                       affiliation
   &lt;chr&gt;                      &lt;chr&gt;      
 1 Lars Eivind Kreken         &amp; co       
 2 Mikael Ernst Joergensen    &amp; co       
 3 Thomas Hoegeboel           &amp; co       
 4 Thomas Hoffmann            &amp; co       
 5 Niels Thorborg             3C Groups  
 6 Soeren Melanchton Pedersen 3C Groups  
 7 Nicoline E. Hyldahl        3C Groups  
 8 Maurizio Botta             3M         
 9 Nicolas Nees Henriksson    3M         
10 Niels Roeddik              3M         
# ℹ 9,514 more rows</code></pre>
</div>
</div>
<p>Det vil vi gerne lave til en biadjacency matrice med individer i rækker og affiliations i kolonnerne. Fordi det bliver en kæmpe tabel med 7641 rækker og 1454 kolonner, bruger vi funktionen <code>xtabs()</code> som gemmer data i hukommelse på en smart måde (hvis vi sætter option <code>spare = TRUE</code>), så vi slipper på at bruge computerhukommelse på alle ‘nullerne’ (det skal I ikke bekymre jer om)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>den_corp_bi <span class="ot">&lt;-</span> den_corp <span class="sc">%&gt;%</span> <span class="fu">xtabs</span>(<span class="at">formula =</span> <span class="sc">~</span>name <span class="sc">+</span> affiliation, <span class="at">sparse =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Som I kan se har den_corp_bi nu 7641 rækker og 1454 kolonner</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>den_corp_bi <span class="sc">%&gt;%</span> <span class="fu">dim</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7641 1454</code></pre>
</div>
</div>
<p>og matricen er fyldt med en masse <code>.</code> fordi den er sparse. De stedet i tabellen hvor der faktisk er en forbindelse mellem <span class="math inline">\(Individ_{i}\)</span> og <span class="math inline">\(Organisation_{j}\)</span> står der tilgengæld <span class="math inline">\(1\)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>den_corp_bi[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">750</span><span class="sc">:</span><span class="dv">770</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>10 x 21 sparse Matrix of class "dgCMatrix"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>  [[ suppressing 21 column names 'KHR arkitekter', 'Kilroy International', 'Kim Johansen' ... ]]</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                          affiliation
name                                                                
  Aage Almtoft             . . . . . . . . . . . . . . . . . . . . .
  Aage Juhl Joergensen     . . . . . . . . . . . . . . . . . . . . .
  Aage Kjaer Soerensen     . . . . . . . . . . . . . . . . . . . . .
  Aage Laurids Andreasen   . . . . . . . . . . . . . . . . . . . . .
  AAke Fredriksson         . . . . . . . . . . . . 1 . . . . . . . .
  AAke Hantoft             . . . . . . . . . . . . . . . . . . . . .
  AAke Marcus Wärring      . . . . . . . . . . . . . . . . . . . . .
  AAke Per-Urban Bäckström . . . . . . . . . . . . . . . . . . . . .
  Aalipaaraq Kreutzmann    . . . . . . . . . . . . . . . . . . . . .
  Aaron Todd Church        . . . . . . . . . . . . . . . . . . . . .</code></pre>
</div>
</div>
<p>Lad os implementere den besværlige matrixregning, nu i effektiv R-kode og dermed lave to adjacency matricer:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>den_corp_ind <span class="ot">&lt;-</span> den_corp_bi <span class="sc">%*%</span> <span class="fu">t</span>(den_corp_bi)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>den_corp_org <span class="ot">&lt;-</span> <span class="fu">t</span>(den_corp_bi) <span class="sc">%*%</span> den_corp_bi</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Det giver os to matricer med dimensionerne</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(den_corp_ind)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7641 7641</code></pre>
</div>
</div>
<p>dvs individ x individ,</p>
<p>og</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(den_corp_org)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1454 1454</code></pre>
</div>
</div>
<p>dvs. organisation x organisation.</p>
</section>
</section>
<section id="netværksobjekter-fra-matricer-igraph" class="level1">
<h1>Netværksobjekter fra matricer (<code>igraph()</code>)</h1>
<p>Nu skal vi til at bruge <code>igraph()</code>-pakken, som har en masse funktioner til at lave og analysere netværksdata:</p>
<section id="monopartite-netværk" class="level2">
<h2 class="anchored" data-anchor-id="monopartite-netværk">(Monopartite) netværk</h2>
<ul>
<li><code>graph_from_adjacency_matrix()</code> tager, som funktionens navn indikerer en adjacency matrice, som dem vi lige har lavet, og giver et netværksobjekt som output. Funktionen har tre vigtige options: <code>mode =</code>, <code>weighted =</code> og <code>diag =</code>,
<ul>
<li>mode kan være enten <code>mode = "directed"</code> eller <code>mode = "undirected"</code>, alt efter om netværket er retningsbestemt eller ej: er A - B og B - A det samme eller to forskellige ting.</li>
<li>weigthed kan være enten <code>weighted = TRUE</code> eller <code>weighted = FALSE</code>, alt efter om det har nogen betydning, hvor mange gange (eller hvor godt) A og B kender hinanden.</li>
<li>diag kan være enten <code>diagonal = TRUE</code> eller <code>diagonal = FALSE</code>, alt efter om vi er interesseret i diagonalen, dvs. A’s forbindelse til sig selv.</li>
</ul></li>
</ul>
<p>I dette tilfælde, hvor vores matrice er en projektion af en medlemskabsliste, har netværket ingen retning. A kender B på samme måde som B kender A, når de sidder sammen i en bestyrelse. Matricen er vægtet, fordi A og B kan kende hinanden flere steder. Og diagonalen, den er vi ikke interesseret i.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>g_ind <span class="ot">&lt;-</span> den_corp_ind <span class="sc">%&gt;%</span> <span class="fu">graph_from_adjacency_matrix</span>(<span class="at">mode =</span> <span class="st">"undirected"</span>, <span class="at">weighted =</span> <span class="cn">TRUE</span>, <span class="at">diag =</span> <span class="cn">FALSE</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>g_ind</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>IGRAPH 145365d UNW- 7641 42967 -- 
+ attr: name (v/c), weight (e/n)
+ edges from 145365d (vertex names):
 [1] Aage Almtoft        --Allan Buch             
 [2] Aage Almtoft        --Bettina Joergensen     
 [3] Aage Almtoft        --Bo Skovby Rosendahl    
 [4] Aage Almtoft        --Bo Smith 4493          
 [5] Aage Almtoft        --Claus Nielsen 50129    
 [6] Aage Almtoft        --Jan Melgaard           
 [7] Aage Almtoft        --Martin Noerholm Baltser
 [8] Aage Almtoft        --Michael Frandsen       
+ ... omitted several edges</code></pre>
</div>
</div>
<p>Et grafobjekt fra Igraph er et særligt dataobjekt, som indeholder to forskellige elementer af data, nemlig vertices og edges. der er 7641 vertices i vores objekt og 42967 edges. Hver af disse elementer kan have forskellige attributes (se + attr:) Som I kan se har vi to attributes <code>name (v/c)</code> og <code>weight (e/n)</code>. (v/c) ved name betyder at det er en attribute til vores <strong>v</strong>ertices og at det er en <code>character</code> vektor (det er en vektor med navne). (e/n) ved weight betyder at det er en attribute til vores <strong>e</strong>dges og at det er en numerisk vektor (en vektor med tal, der indikerer styrken af forbindelsen) <img src="images/Screenshot from 2025-02-04 15-24-37.png" class="img-fluid" style="width:100.0%"> Hvis vi gerne vil tilgå vertex attrubutes i vores grafobjekt skal vi bruge funktionen <code>V()</code> fra <code>igraph</code> efterfulgt af <code>$</code> og navnet på den specifikke attribute her altså <code>$name</code>. Lad os se de første 20 navne.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">V</span>(g_ind)<span class="sc">$</span>name <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Aage Almtoft"                        
 [2] "Aage Juhl Joergensen"                
 [3] "Aage Kjaer Soerensen"                
 [4] "Aage Laurids Andreasen"              
 [5] "AAke Fredriksson"                    
 [6] "AAke Hantoft"                        
 [7] "AAke Marcus Wärring"                 
 [8] "AAke Per-Urban Bäckström"            
 [9] "Aalipaaraq Kreutzmann"               
[10] "Aaron Todd Church"                   
[11] "AAse Aulie Michelet"                 
[12] "AAse Kogsboell"                      
[13] "Abdelmottaleb Doulan"                
[14] "Abdulkareem Hamad A Alayuni"         
[15] "Adam Christian Harhoff"              
[16] "Adam Christoffer Knuth"              
[17] "Adam Hugh Warby"                     
[18] "Adam Price"                          
[19] "Adam Troels Bjerg"                   
[20] "Adamangelo Cavalié Engelhardt 196867"</code></pre>
</div>
</div>
<p>Hvis vi gerne vil tilgå edge attributes i vores grafobjekt skal vi bruge funktionen <code>E()</code> fra <code>igraph</code> efterfulgt af <code>$</code> og navnet på den specifikke attribute her altså <code>$weight</code>. Lad os se de første 20 vægte og derefter et <code>table()</code> over fordelingen.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">E</span>(g_ind)<span class="sc">$</span>weight <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">E</span>(g_ind)<span class="sc">$</span>weight <span class="sc">%&gt;%</span> <span class="fu">table</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>.
    1     2     3     4     5     9 
41325  1441   158    30    12     1 </code></pre>
</div>
</div>
<p>Der er altså mange, der kender hinanden fra en organisation, nogle kender hinanden fra to og ganske ganske få fra tre eller flere.</p>
<p>vi kan også lave et graf-objekt for <span class="math inline">\(organisation \times organisation\)</span>-matricen:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>g_org <span class="ot">&lt;-</span> den_corp_org <span class="sc">%&gt;%</span> <span class="fu">graph_from_adjacency_matrix</span>(<span class="at">mode =</span> <span class="st">"undirected"</span>, <span class="at">weighted =</span> <span class="cn">TRUE</span>, <span class="at">diag =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>lad os igen lige se vertex navne og edge vægte:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">V</span>(g_org)<span class="sc">$</span>name <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "&amp; co"                                
 [2] "3C Groups"                           
 [3] "3M"                                  
 [4] "3xN"                                 
 [5] "5E Byg (Bestyrelse)"                 
 [6] "7N"                                  
 [7] "A-pressen"                           
 [8] "A. Enggaard Holding"                 
 [9] "A.P. Moeller - Maersk"               
[10] "A.R. HOLDING AF 1999 A/S"            
[11] "A/S DANSK ERHVERVSINVESTERING"       
[12] "A/S POLITIKEN HOLDING"               
[13] "A/S Silvagra"                        
[14] "A2SEA A/S"                           
[15] "AAGE OG JOHANNE LOUIS-HANSENS FOND"  
[16] "Aalborg Engineering (bestyrelse)"    
[17] "Aalborg Forsyning"                   
[18] "Aalborg Portland"                    
[19] "Aalborg Stiftstidende"               
[20] "Aalborg Zoologiske Have (Bestyrelse)"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">E</span>(g_org)<span class="sc">$</span>weight <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 1 1 1 1 1 1 1 1 1 1 4 1 2 2 1 1 1 1 1 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">E</span>(g_org)<span class="sc">$</span>weight <span class="sc">%&gt;%</span> <span class="fu">table</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>.
   1    2    3    4    5    6    7    8    9   10   11   13   15   17 
2247  229   98   35   24   14    9    4    5    3    1    2    1    1 </code></pre>
</div>
</div>
<p>Hovedparten forbindelserne mellem organisationer skyldes altså ét overlappende medlem, nogle skyldes to og ganske få skyldes mere end to overlappende medlemmer (en enkelt forbindelse skyldes hele 17 fælles medlemmer)</p>
</section>
<section id="bipartite-netværk" class="level2">
<h2 class="anchored" data-anchor-id="bipartite-netværk">(Bipartite) netværk</h2>
<p>Endelig kan vi faktisk også lave et graf-objekt ud fra den oprindelige <span class="math inline">\(individ \times organisation\)</span> biadjacency matrice</p>
<p>til det bruges funktionen:</p>
<ul>
<li><code>graph_from_biadjacency_matrix()</code></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>g_bi <span class="ot">&lt;-</span> den_corp_bi <span class="sc">%&gt;%</span> <span class="fu">graph_from_biadjacency_matrix</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="netværksvisualisering" class="level1">
<h1>Netværksvisualisering</h1>
<p>Lad os lige kort se på et par visualiseringer. Til det formål bruger vi <code>ggraph()</code>-pakken. Den vender vi tilbage til i løbet af kurset, så det udfoldes ikke yderligere her</p>
<p><span class="math inline">\(individ \times individ\)</span> netværket</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>g_ind_l <span class="ot">&lt;-</span> <span class="fu">largest_component</span>(g_ind) </span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggraph</span>(g_ind_l, <span class="at">layout =</span> <span class="st">"fr"</span>) <span class="sc">+</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_edge_link0</span>(<span class="at">edge_alpha =</span> <span class="fl">0.2</span>, <span class="at">edge_width =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_node_point</span>(<span class="at">size =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_graph</span>() </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="session1_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><span class="math inline">\(organisation \times organisation\)</span> netværket</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>g_org_l <span class="ot">&lt;-</span> <span class="fu">largest_component</span>(g_org) </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggraph</span>(g_org_l, <span class="at">layout =</span> <span class="st">"fr"</span>) <span class="sc">+</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_edge_link0</span>(<span class="at">edge_alpha =</span> <span class="fl">0.6</span>, <span class="at">edge_width =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_node_point</span>(<span class="at">size =</span> <span class="fl">0.1</span>) <span class="sc">+</span> </span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_graph</span>() </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="session1_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><span class="math inline">\(individ \times organisation\)</span>-netværket</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>g_bi_l <span class="ot">&lt;-</span> <span class="fu">largest_component</span>(g_bi)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggraph</span>(g_bi_l, <span class="at">layout =</span> <span class="st">"fr"</span>) <span class="sc">+</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_edge_link0</span>(<span class="at">edge_alpha =</span> <span class="fl">0.8</span>, <span class="at">edge_width =</span> <span class="fl">0.1</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_node_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> type), <span class="at">size =</span> <span class="fl">0.2</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">"sienna1"</span>, <span class="st">"steelblue2"</span>), <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"individuals"</span>, <span class="st">"companies"</span>)) <span class="sc">+</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_graph</span>() </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="session1_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>